# Generated by Django 4.0.2 on 2022-09-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Ranking_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
