# Generated by Django 4.0.2 on 2022-09-29 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Ranking_System', '0002_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mode', models.ManyToManyField(to='Game_Ranking_System.GameMode')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.IntegerField()),
                ('p2_score', models.IntegerField()),
                ('p1_character', models.CharField(max_length=150)),
                ('p2_character', models.CharField(max_length=150)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('p1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_id', to=settings.AUTH_USER_MODEL)),
                ('p2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_confirmed', models.BooleanField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to=settings.AUTH_USER_MODEL)),
                ('game_mode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game_Ranking_System.gamemode')),
                ('game_title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game_Ranking_System.gametitle')),
                ('opponent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_id', to=settings.AUTH_USER_MODEL)),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game_Ranking_System.score')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=150)),
                ('game_mode', models.CharField(max_length=150)),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game_Ranking_System.score')),
            ],
        ),
    ]
