# Generated by Django 4.0.2 on 2022-10-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Ranking_System', '0005_auto_20221021_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
