# Generated by Django 4.0.2 on 2022-10-25 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Ranking_System', '0006_auto_20221023_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='personal_opponent_nickname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='p2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
