# Generated by Django 4.0.2 on 2022-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Ranking_System', '0008_auto_20221025_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='public_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gametitle',
            name='public_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
