# Generated by Django 4.0.2 on 2022-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Ranking_System', '0009_auto_20221026_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
